theme: jekyll-theme-cayman
title: Barnabas Hang
description: <img class="_11kf img" alt="your profile photo, Image may contain: 1 person, smiling" src="https://scontent-vie1-1.xx.fbcdn.net/v/t1.0-1/p160x160/11390227_981728731878946_5173660834069269193_n.jpg?_nc_cat=107&amp;_nc_ht=scontent-vie1-1.xx&amp;oh=ec2558324f2c242aeb4765ae25476be6&amp;oe=5CFAE3A0">Software Developer
